## Get all contacts
GET http://localhost:3000/users

## Get single contact
GET http://localhost:3000/users/67900cf7cb7b3a7172b265de

## Create contact
POST http://localhost:3000/users HTTP/1.1
content-type: application/json

{
    "firstName": "Peter",
    "lastName": "Parker",
    "email": "peterparker@gmail.com",
    "favoriteColor": "red",
    "birthday": "January 10, 1990"
}

##Updat contact
PUT http://localhost:3000/users/67900f820cef38827f399eea HTTP/1.1
content-type: application/json

{
    "firstName": "Scott",
    "lastName": "Lang",
    "email": "scottlang@gmail.com",
    "favoriteColor": "orange",
    "birthday": "May 5, 1978"
}

## Delete single contact
DELETE http://localhost:3000/users/679aa4795e4a7df676385a2b HTTP/1.1